# Creates an HTML report
# with analysis of commit statistics.
#
# More information: https://github.com/bakhirev/assayo
name: Assayo

on:
  # Run by time
  # (if you have a lot of people and frequent commits)
  # Remove this for small teams:
  schedule:
  - cron: '0 0 */5 * *'

  # Run by PR
  # (if you have few people and commits are rarely made)
  # Remove this for big teams:
  pull_request:
    types: [closed]
  push:
    tags:
      - '*'
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create report
      uses: bakhirev/assayo@v0.0.2
      with:
        add_file_info: true
