export const TEAM = [
  {
    id: 'total',
    link: '/team/total',
    title: 'sidebar.team.total',
    icon: './assets/menu/team_common.svg',
  },
  {
    id: 'scope',
    link: '/team/scope',
    title: 'sidebar.team.scope',
    icon: './assets/menu/team_feat.svg',
  },
  {
    id: 'author',
    link: '/team/author',
    title: 'sidebar.team.author',
    icon: './assets/menu/team_work.svg',
  },
  {
    id: 'type',
    link: '/team/type',
    title: 'sidebar.team.type',
    icon: './assets/menu/team_type.svg',
  },
  {
    id: 'pr',
    link: '/team/pr',
    title: 'sidebar.team.pr',
    icon: './assets/menu/pull_request.svg',
  },
  {},
  {
    id: 'day',
    link: '/team/day',
    title: 'sidebar.team.day',
    icon: './assets/menu/team_week.svg',
  },
  {
    id: 'week',
    link: '/team/week',
    title: 'sidebar.team.week',
    icon: './assets/menu/team_week.svg',
  },
  {
    id: 'month',
    link: '/team/month',
    title: 'sidebar.team.month',
    icon: './assets/menu/team_date_1.svg',
  },
  {
    id: 'hours',
    link: '/team/hours',
    title: 'sidebar.team.hours',
    icon: './assets/menu/team_date_2.svg',
  },
  {},
  {
    id: 'tree',
    link: '/team/tree',
    title: 'sidebar.team.tree',
    icon: './assets/menu/team_files.svg',
  },
  {
    id: 'commits',
    link: '/team/commits',
    title: 'sidebar.team.commits',
    icon: './assets/menu/pull-request.svg',
  },
  {
    id: 'changes',
    link: '/team/changes',
    title: 'sidebar.team.changes',
    icon: './assets/menu/branch.svg',
  },
  {
    id: 'words',
    link: '/team/words',
    title: 'sidebar.team.words',
    icon: './assets/menu/team_words.svg',
  },
];

export const PERSON = [
  {
    id: 'total',
    link: '/person/total/',
    title: 'sidebar.person.total',
    icon: './assets/menu/team_common.svg',
  },
  {
    id: 'money',
    link: '/person/money/',
    title: 'sidebar.person.money',
    icon: './assets/menu/per_money.svg',
  },
  {
    id: 'speed',
    link: '/person/speed/',
    title: 'sidebar.person.speed',
    icon: './assets/menu/per_speed.svg',
  },
  {},
  {
    id: 'day',
    link: '/person/day/',
    title: 'sidebar.person.day',
    icon: './assets/menu/team_week.svg',
  },
  {
    id: 'week',
    link: '/person/week/',
    title: 'sidebar.person.week',
    icon: './assets/menu/team_week.svg',
  },
  {
    id: 'month',
    link: '/person/month/',
    title: 'sidebar.person.month',
    icon: './assets/menu/team_date_1.svg',
  },
  {
    id: 'hours',
    link: '/person/hours/',
    title: 'sidebar.person.hours',
    icon: './assets/menu/team_date_2.svg',
  },
  {},
  {
    id: 'commits',
    link: '/person/commits/',
    title: 'sidebar.person.commits',
    icon: './assets/menu/pull-request.svg',
  },
  {
    id: 'changes',
    link: '/person/changes/',
    title: 'sidebar.person.changes',
    icon: './assets/menu/branch.svg',
  },
  {
    id: 'words',
    link: '/person/words/',
    title: 'sidebar.person.words',
    icon: './assets/menu/team_words.svg',
  },
];